# Generated by Django 3.1 on 2023-03-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qflexApp', '0002_auto_20230301_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='isRecommended',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Recommended'),
        ),
    ]
